package de.bsommerfeld.randomizer.exec;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

class ExecConfigTest {

    @TempDir
    Path tempDir;

    @Test
    void writesCommandsInMapOrderIntoTheCfgFolder() throws IOException {
        ExecConfig config = new ExecConfig(() -> Optional.of(tempDir));
        Map<String, String> values = new LinkedHashMap<>();
        values.put("cl_crosshairsize", "3");
        values.put("cl_crosshairgap", "-2.5");

        Optional<Path> written = config.write(values);

        assertEquals(Optional.of(tempDir.resolve("randomizer.cfg")), written);
        List<String> lines = Files.readAllLines(written.orElseThrow());
        assertEquals(List.of(
                "// Generated by Randomizer CS2 - exec randomizer",
                "cl_crosshairsize \"3\"",
                "cl_crosshairgap \"-2.5\""), lines);
    }

    @Test
    void writeReplacesAnEarlierFile() throws IOException {
        ExecConfig config = new ExecConfig(() -> Optional.of(tempDir));
        config.write(Map.of("cl_crosshairsize", "3"));

        config.write(Map.of("cl_crosshairsize", "7"));

        assertTrue(Files.readString(tempDir.resolve("randomizer.cfg")).contains("\"7\""));
    }

    @Test
    void writesNothingWhenCfgFolderIsUnresolvable() throws IOException {
        ExecConfig config = new ExecConfig(Optional::empty);

        assertTrue(config.write(Map.of("cl_crosshairsize", "3")).isEmpty());
        try (var files = Files.list(tempDir)) {
            assertTrue(files.findAny().isEmpty());
        }
    }

    @Test
    void stripsUnsafeCharactersFromValues() {
        String rendered = ExecConfig.render(Map.of("cl_crosshairsize", "3\";echo \"pwn\\\r\nquit"));

        assertEquals("// Generated by Randomizer CS2 - exec randomizer\ncl_crosshairsize \"3echo pwnquit\"\n",
                rendered);
    }
}
