package de.bsommerfeld.randomizer.exec;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Map;
import java.util.Optional;
import java.util.function.Supplier;

/**
 * Writes convar values as an {@code exec}-able console config ({@code randomizer.cfg}) into CS2's
 * cfg folder. Running {@code exec randomizer} in-game applies the values immediately, and CS2
 * persists them itself on exit. Config-type agnostic: what is written is defined entirely by the
 * value map.
 *
 * <p>The cfg-folder supplier is evaluated on every write, so a Steam/game move is picked up
 * without an app restart.
 */
public final class ExecConfig {

    /** Name used in-game: {@code exec randomizer}. */
    public static final String EXEC_NAME = "randomizer";
    public static final String FILE_NAME = EXEC_NAME + ".cfg";

    private final Supplier<Optional<Path>> cfgFolder;

    public ExecConfig(Supplier<Optional<Path>> cfgFolder) {
        this.cfgFolder = cfgFolder;
    }

    /**
     * Writes {@code values} as {@link #FILE_NAME} into the cfg folder and returns the written
     * file, or empty (without writing) if the folder cannot be resolved.
     */
    public Optional<Path> write(Map<String, String> values) throws IOException {
        Optional<Path> folder = cfgFolder.get();
        if (folder.isEmpty()) {
            return Optional.empty();
        }
        Path target = folder.get().resolve(FILE_NAME);
        Files.writeString(target, render(values), StandardCharsets.UTF_8);
        return Optional.of(target);
    }

    /**
     * Renders the values as console commands, {@code key "value"} in map order. Values are
     * sanitized ({@code "}, {@code ;}, {@code \} and line breaks stripped) - the Source console
     * has no reliable escape syntax, and legitimate convar values never contain these.
     */
    static String render(Map<String, String> values) {
        StringBuilder sb = new StringBuilder("// Generated by Randomizer CS2 - exec " + EXEC_NAME + "\n");
        values.forEach((key, value) -> sb.append(key).append(" \"").append(sanitize(value)).append("\"\n"));
        return sb.toString();
    }

    private static String sanitize(String value) {
        return value.replaceAll("[\";\\\\\r\n]", "");
    }
}
