name: CI Build and Release

on:
  push:
    branches:
      - "stage"

jobs:
  build:

    name: Build
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clean workspace
        run: git clean -fdx

      - name: Set up JDK 22
        uses: actions/setup-java@v1
        with:
          distribution: 'corretto'
          java-package: 'jdk+fx'
          java-version: '24'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.4
        with:
          maven-version: 3.8.6

      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml', '**/*.target') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Clean install
        run: mvn clean install -U

      - name: Build Updater
        run: mvn -U -V -e -B -ntp clean install compile package -pl randomizer-desktop/randomizer-updater -amd -DskipTests

      - name: Build Randomizer
        run: mvn -U -V -e -B -ntp clean install compile package -pl randomizer-desktop/randomizer -amd -DskipTests

      - name: Upload Randomizer
        uses: actions/upload-artifact@v4
        with:
          name: randomizer
          path: D:\a\randomizer-cs2\randomizer-cs2\randomizer-desktop\randomizer\target\randomizer.jar

      - name: Upload Updater
        uses: actions/upload-artifact@v4
        with:
          name: updater
          path: D:\a\randomizer-cs2\randomizer-cs2\randomizer-desktop\randomizer-updater\target\randomizer-updater.jar

  pre-release:
    name: Pre Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Randomizer
        uses: actions/download-artifact@v4
        with:
          name: randomizer

      - name: Download Updater
        uses: actions/download-artifact@v4
        with:
          name: updater

      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Latest Release"
          files: |
            *.jar