# THIS IS A DEBUGGING WORKFLOW - Step 1: Isolate Discord Action Issue
# It lets jDeploy create the release, then verifies, then tries to send to Discord.
# Custom changelog generation and our body modification are temporarily disabled.

name: Release CI - DEBUG Discord

on:
  push:
    tags:
      - '*'

permissions:
  contents: write # Required for creating/editing GitHub releases and for jDeploy

jobs:
  build_and_release:
    name: Build, Release and Notify (Debug Discord Only)
    runs-on: ubuntu-latest
    outputs:
      release_body_verified_by_jdeploy: ${{ steps.verify_jdeploy_release_body.outputs.body_is_set }}
      release_tag: ${{ github.ref_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for full history if changelog were active

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # -----------------------------------------------------------------------------------
      # --- Custom Changelog Generation and Body Modification ARE TEMPORARILY DISABLED ---
      # - name: Determine Previous SemVer Tag for Changelog (Diagnosis)
      #   id: previous_tag_detector
      #   ...
      # - name: Generate categorized changelog to file
      #   id: changelog_generator
      #   ...
      # - name: Display Generated Changelog
      #   ...
      # - name: Combine Our Changelog with jDeploy Notes and Update Release Body
      #   id: combine_and_update_release
      #   ...
      # -----------------------------------------------------------------------------------

      - name: Build App Installer Bundles and Create/Update GitHub Release (jDeploy)
        id: jdeploy_release
        uses: shannah/jdeploy@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # jDeploy will create/update the release for GITHUB_REF_NAME
          # and set its own default release notes.

      - name: Verify jDeploy-Set Release Body
        id: verify_jdeploy_release_body
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "VERIFYING Release Body Content AFTER jDeploy has run (no modification by our workflow):"
          TAG_NAME="${{ github.ref_name }}"
          echo "Fetching release for tag: ${TAG_NAME}"
          
          VERIFIED_BODY=$(gh release view "${TAG_NAME}" --json body --template '{{.body}}')
          
          if [ -z "$(echo -e "${VERIFIED_BODY}" | tr -d '[:space:]')" ]; then
            echo "ERROR: Release body set by jDeploy appears EMPTY or whitespace-only!"
            echo "Raw verified body by jDeploy: <<EOF"
            echo "${VERIFIED_BODY}"
            echo "EOF"
            echo "::set-output name=body_is_set::false"
          else
            echo "SUCCESS: Release body set by jDeploy is NOT empty. Content:"
            echo "------------------- VERIFIED JDEPLOY BODY START -------------------"
            echo -e "${VERIFIED_BODY}"
            echo "-------------------- VERIFIED JDEPLOY BODY END --------------------"
            echo "::set-output name=body_is_set::true"
          fi
          echo "-------------------------------------------------"

      - name: Send GitHub Release to Discord (using jDeploy's original body)
        # This step now uses the release body as set *only* by jDeploy.
        if: steps.verify_jdeploy_release_body.outputs.body_is_set == 'true'
        uses: SethCohen/github-releases-to-discord@v1.16.2
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          color: "2105893"
          username: "Randomizer-CS2"
          avatar_url: "https://raw.githubusercontent.com/bsommerfeld/randomizer-cs2/refs/heads/master/.randomizer/design/logo/randomizer.png"
          content: "@everyone"
          footer_title: "Changelog (jDeploy Default)"
          footer_icon_url: "https://raw.githubusercontent.com/bsommerfeld/randomizer-cs2/refs/heads/master/.randomizer/design/logo/randomizer.png"
          footer_timestamp: true
          max_description: '4096'
          reduce_headings: true
